### ISSUE TITLE
Add postgres integration to backend with 'go-pg'

### ISSUE THREAD

**Issue by jgwest** [redhat-appstudio/managed-gitops#1]
- Add https://github.com/go-pg/pg to go.mod of 'backend'
- Next, write a function that uses go-pg to connect to our database (see above URL for examples of how to do this)

The backend folder is VERY barebones at the moment... it's just a very simple module based on a tiny example from the go-restful project, just enough for us to get started. Feel free to create new Go packages,  move stuff around in there, etc.

**Comment by samyak-jn** [comment]
Hey Hi, I'll give this a try, and hence assigning this issue to myself! :taco:
