### ISSUE TITLE
Add REST endpoints to Go backend

### ISSUE THREAD

**Issue by jgwest** [redhat-appstudio/managed-gitops#4]
- Implement the REST endpoints from https://docs.google.com/document/d/1e1UwCbwK-Ew5ODWedqp_jZmhiZzYWaxEvIL-tqebMzo/edit#heading=h.mzse2565h9bp using `go-restful`
- See  https://github.com/emicklei/go-restful for examples

This work includes defining structs for the JSON values returned by the endpoints:
```go

package api

// struct corresponding to the JSON respresentation of the User
type User struct {
	// JSON representation of fields from DB
}

// struct corresponding to the JSON representation of the Application
type Application {

	// JSON representation of fields from DB
	
	// name
	// spec contents
	// etc
	
	// (same fields as DB)
}

// etc

```

In order to verify the endpoints are working as expected, [Postman](https://www.postman.com/product/rest-client/) or [a similar utility](https://alternativeto.net/software/postman/?license=opensource) can be used.

**Comment by samyak-jn** [comment]
Hey hi, I would like to give this issue a try, assigning myself! :taco: 
Please let me know in case of any conflict :hugs:

**Comment by jgwest** [comment]
Done :tada:
